### ISSUE TITLE
Hello, can someone give me brief instructions on how to make this work?

### ISSUE THREAD

**Issue by simonasbuj** [idleberg/atom-build-fpc#1]
Im new to Atom and its kinda confusing for me.

I installed this package along side all other packages that were required (build0.7 and another one)

I open my project location, select .pas file and click ctrl+alt+T but it says "no targets found"
When i click ctrl+alt+b to build it throws an error. 
Please help me to understand how to run .pas file. thank you for any information

I added fpc.exe file to path variable, but its still not workin

It started working for some reason now. And by working it shows Free Pascal when i press ctrl+alt+T. But when i build it throws this error:
Unable to execute: fpc
Make sure cmd:'fpc' and cwd:'{FILE_ACTIVE_PATH}' exists and have correct access permissions.

alright it started working for no reason, even though I change nothing. It compiles and everything. But i thought that it would ask for user input if it has readln(); was I wrong?

**Comment by idleberg** [comment]
> But i thought that it would ask for user input if it has readln(); was I wrong?

For user input, you would need to use an Atom package that provides a [REPL](https://www.wikiwand.com/en/Read%E2%80%93eval%E2%80%93print_loop). Unfortunately, I'm unaware of existing packages.
